const {test}=require('node:test'),assert=require('node:assert/strict')
const {mkdtemp,writeFile}=require('node:fs/promises'),{tmpdir}=require('node:os'),{join}=require('node:path')
const {Store}=require('../electron/store.cjs'),{Attachments}=require('../electron/attachments.cjs'),{Copilot,validateSettings,turnOptions}=require('../electron/copilot.cjs'),{Runtime}=require('../electron/runtime.cjs')
const models=[{id:'one',model:'one',displayName:'One',isDefault:true,defaultReasoningEffort:'medium',supportedReasoningEfforts:[{reasoningEffort:'low'},{reasoningEffort:'medium'}],inputModalities:['text','image']},{id:'two',model:'two',defaultReasoningEffort:'high',supportedReasoningEfforts:[{reasoningEffort:'high'}],inputModalities:['text']}]
async function fixture(){const dir=await mkdtemp(join(tmpdir(),'servers-copilot-'));const store=new Store(join(dir,'data.json'));return{dir,store,files:new Attachments(store,join(dir,'attachments'))}}
test('settings validate against model capabilities and native mode settings match outer overrides',()=>{assert.throws(()=>validateSettings({model:'absent',mode:'default'},models));assert.throws(()=>validateSettings({model:'two',effort:'low',mode:'default'},models));const s=validateSettings({model:'one',effort:'low',mode:'plan'},models);const o=turnOptions(s);assert.equal(o.model,o.collaborationMode.settings.model);assert.equal(o.effort,o.collaborationMode.settings.reasoning_effort);assert.equal(o.collaborationMode.mode,'plan');assert.equal(o.collaborationMode.settings.developer_instructions,null)})
test('catalog paginates, hides hidden entries, persists per-session choices and rejects plan mutations',async()=>{const {store,files}=await fixture();const runtime={questions:new Map(),request:async(method,p)=>method==='model/list'?(p.cursor?{data:[models[1]],nextCursor:null}:{data:[models[0],{...models[1],hidden:true}],nextCursor:'next'}):{data:[{mode:'plan'},{mode:'default'}]}};const c=new Copilot(runtime,store,files);assert.equal((await c.catalog()).models.length,2);await c.settings('a',{model:'one',effort:'low',mode:'plan'});await c.settings('b',{model:'two',effort:'high',mode:'default'});assert.equal((await c.snapshot('a')).settings.mode,'plan');assert.equal((await c.snapshot('b')).settings.model,'two');assert.equal((await c.snapshot('new')).running,false);c.threadModes.set('t','plan');assert.throws(()=>c.checkTool('t','servers_exec'));assert.throws(()=>c.checkTool('t','servers_upsert'));c.checkTool('t','servers_inspect_hardware')})
test('attachments snapshot content, isolate owners, validate modalities and retain draft until accepted',async()=>{const{dir,files}=await fixture();const path=join(dir,'error.log');await writeFile(path,'fixture log 583');const[a]=await files.add('a',[{path}]);assert.equal(a.path,undefined);await writeFile(path,'changed source');assert.match((await files.inputs('a',[a.id],models[0]))[0].text,/fixture log 583/);await assert.rejects(files.inputs('b',[a.id],models[0]));assert.equal((await files.list('a')).length,1);await files.markSent('a',[a.id]);assert.equal((await files.list('a')).length,0);assert.match((await files.preview('a',a.id)).text,/583/);await assert.rejects(files.remove('a',a.id));const image=Buffer.from([137,80,78,71,13,10,26,10,1]);const[b]=await files.add('a',[{png:image.toString('base64')}]);await assert.rejects(files.inputs('a',[b.id],models[1]));assert.equal((await files.inputs('a',[b.id],models[0]))[0].type,'localImage');await files.remove('a',b.id);assert.equal((await files.list('a')).length,0)})
test('unsupported documents, oversized batches and private keys are rejected',async()=>{const{dir,files}=await fixture();const path=join(dir,'secret.txt');await writeFile(path,'-----BEGIN OPENSSH PRIVATE KEY-----\nsecret');await assert.rejects(files.add('a',[{path}]),/私钥/);await writeFile(join(dir,'doc.pdf'),'%PDF');await assert.rejects(files.add('a',[{path:join(dir,'doc.pdf')}]),/PDF/);await assert.rejects(files.add('a',Array(11).fill({path})));await assert.rejects(files.add('../escape',[{path}]))})
test('native question replies validate all answers and never accept stale ids',()=>{const r=new Runtime('unused','unused'),sent=[];r.rpc={send:v=>sent.push(v)};r.questions.set(3,{params:{questions:[{id:'q'}]}});assert.throws(()=>r.answer(3,{}));r.answer(3,{q:{answers:['selected']}});assert.deepEqual(sent[0],{id:3,result:{answers:{q:{answers:['selected']}}}});assert.throws(()=>r.answer(3,{q:{answers:['again']}}))})
test('native goal and plan events persist separately for each conversation',async()=>{const{store,files}=await fixture(),c=new Copilot({questions:new Map()},store,files);await c.event({method:'thread/goal/updated',params:{goal:{objective:'goal',status:'active'}}},'a');await c.event({method:'turn/plan/updated',params:{turnId:'turn1',plan:[{step:'inspect',status:'inProgress'}]}},'b');const restored=new Copilot({questions:new Map()},store,files);assert.equal((await restored.snapshot('a')).goal.objective,'goal');assert.equal((await restored.snapshot('b')).goal,undefined);assert.equal((await restored.snapshot('b')).plan[0].status,'inProgress')})
test('quota normalization prefers all buckets, preserves unavailable values and clamps remaining',async()=>{const{quotaBuckets,remaining,duration}=await import('../src/lib/quotas.mjs');assert.equal(quotaBuckets({rateLimitsByLimitId:{a:{},b:{}},rateLimits:{}}).length,2);assert.equal(remaining({usedPercent:null}),null);assert.equal(remaining({usedPercent:25}),75);assert.equal(remaining({usedPercent:105}),0);assert.equal(duration(10080),'每周');assert.equal(duration(300),'5 小时')})
test('queued attachments are hidden from drafts until canceled or failed',async()=>{
 const {Copilot}=require('../electron/copilot.cjs')
 const data={runs:[{conversationId:'chat',status:'queued',value:{attachments:['locked']}}]}
 const cp=new Copilot({state:'stopped',questions:new Map()},{read:async()=>data},{list:async()=>[{id:'locked'},{id:'draft'}]})
 assert.deepEqual((await cp.snapshot('chat')).attachments,[{id:'draft'}])
 data.runs[0].status='failed'
 assert.deepEqual((await cp.snapshot('chat')).attachments,[{id:'locked'},{id:'draft'}])
})
