const { test } = require('node:test')
const assert = require('node:assert/strict')
const { mkdtemp } = require('node:fs/promises')
const { join } = require('node:path')
const { tmpdir } = require('node:os')
const { parseHardware, hardwareChecks, buildSshArgs } = require('../electron/ssh.cjs')
const { Store } = require('../electron/store.cjs')
const { ServerTools } = require('../electron/server-tools.cjs')
function section(name, text, code = 0) { return `__SERVERS_BEGIN_${name}__\n${text}\n__SERVERS_END_${name}__:${code}\n` }
test('parses measured CPU, memory and load without conflating load with utilization', () => {
  const text = section('cpu', 'Architecture: x86_64\nCPU(s): 8\nModel name: Test CPU') + section('memory', 'Mem: 16000000000 4000000000 2000000000 0 10000000000 12000000000') + section('load', 'uptime text\n0.25 0.50 0.75 1/200 77') + section('disks', '{"blockdevices":[{"name":"sda","size":100000}]}') + section('filesystems', '/dev/sda 100000 1000 99000 1% /') + section('system', 'Linux test') + section('activity', 'vmstat sample')
  const data = parseHardware(text)
  assert.equal(data.status, 'complete'); assert.deepEqual(data.missingSections, [])
  assert.equal(data.summary.logicalCpus, 8); assert.equal(data.summary.memory.availableBytes, 12000000000)
  assert.deepEqual(data.summary.loadAverage, [0.25, 0.5, 0.75]); assert.equal(data.summary.cpuPercent, undefined)
})
test('preserves partial failures and distinguishes missing output from zero usage', () => {
  const data = parseHardware(section('cpu', 'lscpu: not found', 127) + section('memory', 'Mem: 100 25 25 0 50 75'))
  assert.equal(data.status, 'partial'); assert.equal(data.sections.cpu.exitCode, 127)
  assert.equal(data.summary.cpuModel, undefined); assert.equal(data.summary.memory.totalBytes, 100)
  assert.equal(parseHardware('unexpected login banner').status, 'failed')
})
test('hardware profile exposes only fixed read-only commands', () => {
  const config = { name: 'test', host: 'example.invalid', user: 'admin', authType: 'sshAgent' }
  const args = buildSshArgs(config, 'hardware')
  for (const command of Object.values(hardwareChecks)) assert.ok(args.at(-1).includes(command))
  assert.ok(args.includes('StrictHostKeyChecking=yes'))
  assert.throws(() => buildSshArgs(config, 'sudo reboot'), /不支持/)
  assert.throws(() => buildSshArgs(config, '__proto__'), /不支持/)
})
test('tool persists timestamped summary, audits collection and invalidates changed targets', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'hardware-store-')), store = new Store(join(directory, 'data.json'))
  const server = await store.saveServer({ name: 'test', host: 'example.invalid', user: 'admin', authType: 'sshAgent' })
  const tools = new ServerTools(store, null, () => {}, undefined, async () => ({ status: 'partial', summary: { logicalCpus: 8 }, sections: { cpu: { output: 'raw data' } }, missingSections: ['activity'], checkedAt: '2026-09-14T00:00:00Z', message: '部分完成' }))
  const result = await tools.execute({ tool: 'servers_inspect_hardware', arguments: { id: server.id } })
  assert.equal(result.hardware.status, 'partial'); assert.equal(result.server.lastHardware.summary.logicalCpus, 8)
  assert.equal(result.server.lastHardware.sections, undefined)
  await store.upsertServer({ id: server.id, notes: 'unchanged target' })
  assert.equal((await store.read()).servers[0].lastHardware.summary.logicalCpus, 8)
  await store.upsertServer({ id: server.id, host: 'changed.invalid' })
  await assert.rejects(store.recordHardware(server, result.hardware), /发生变化/)
  assert.equal((await store.read()).servers[0].lastHardware, undefined)
})
