const test = require('node:test')
const assert = require('node:assert/strict')
const { mkdtemp, writeFile, realpath } = require('node:fs/promises')
const { tmpdir } = require('node:os')
const { join } = require('node:path')
const { execFile } = require('node:child_process')
const { promisify } = require('node:util')
const { generateKeyPairSync, createHash } = require('node:crypto')
const { protectFile, prepareManagedKey, setManagedKeyDirectory } = require('../electron/key-permissions.cjs')
const exec=promisify(execFile)
test('managed Windows keys lose unrelated explicit access and become acceptable to OpenSSH', {skip:process.platform!=='win32'}, async()=>{
 // Hosted Windows runners may expose TEMP through an 8.3 alias; use a canonical managed root.
 const dir=await realpath(await mkdtemp(join(tmpdir(),'serverloom-acl-'))),file=join(dir,'synthetic key'),outside=join(tmpdir(),'external-'+Date.now()+'.fixture')
 const bytes=generateKeyPairSync('rsa',{modulusLength:2048}).privateKey.export({type:'pkcs1',format:'pem'})
 await writeFile(file,bytes);await writeFile(outside,'synthetic external fixture')
 const system=join(process.env.SystemRoot,'System32')
 await protectFile(dir)
 await exec(join(system,'icacls.exe'),[file,'/grant','*S-1-1-0:(R)'],{windowsHide:true})
 const binary=join(system,'OpenSSH/ssh-keygen.exe')
 await assert.rejects(exec(binary,['-y','-f',file],{windowsHide:true}),e=>/UNPROTECTED PRIVATE KEY|bad permissions/i.test(e.stderr))
 setManagedKeyDirectory(dir)
 const prior=(await exec(join(system,'icacls.exe'),[outside],{windowsHide:true})).stdout
 await prepareManagedKey(outside)
 assert.equal((await exec(join(system,'icacls.exe'),[outside],{windowsHide:true})).stdout,prior)
 await Promise.all([prepareManagedKey(file),prepareManagedKey(file)])
 assert.match((await exec(binary,['-y','-f',file],{windowsHide:true})).stdout,/^ssh-rsa /)
 const after=await require('node:fs/promises').readFile(file)
 assert.equal(createHash('sha256').update(after).digest('hex'),createHash('sha256').update(bytes).digest('hex'))
})
