const { test } = require('node:test')
const assert = require('node:assert/strict')
const { mkdtemp, writeFile } = require('node:fs/promises')
const { join } = require('node:path')
const { tmpdir } = require('node:os')
const { Store } = require('../electron/store.cjs')
const { ServerTools } = require('../electron/server-tools.cjs')
const { buildSshArgs, classifyFailure, probeCommand, validateKeyPath } = require('../electron/ssh.cjs')
const base = { name: 'home-server', host: '192.0.2.10', user: 'admin', port: 22, authType: 'privateKey' }
test('known key path binds without a picker and connection results persist', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'servers-ssh-')), key = join(dir, 'key with spaces')
  await writeFile(key, 'SYNTHETIC TEST KEY; DO NOT USE FOR AUTHENTICATION')
  const store = new Store(join(dir, 'data.json')); const server = await store.saveServer(base)
  const tools = new ServerTools(store, () => { throw new Error('Picker must not open') }, () => {}, async snapshot => {
    assert.equal(snapshot.privateKeyPath, key)
    return { status: 'passed', message: 'SSH test passed', checkedAt: new Date().toISOString(), remoteUser: 'admin' }
  })
  await tools.execute({ tool: 'servers_bind_private_key', arguments: { id: server.id, path: key } })
  const result = await tools.execute({ tool: 'servers_test_connection', arguments: { id: server.id } })
  assert.equal(result.connected, true); assert.equal(result.persistentSession, false)
  assert.equal((await store.read()).servers[0].lastConnection.status, 'passed')
  await store.upsertServer({ id: server.id, notes: 'metadata-only edit' })
  assert.equal((await store.read()).servers[0].lastConnection.status, 'passed')
  await store.upsertServer({ id: server.id, host: '192.0.2.11' })
  assert.equal((await store.read()).servers[0].lastConnection, undefined)
})
test('changed target during an in-flight test cannot receive a stale success', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'servers-race-')), store = new Store(join(dir, 'data.json'))
  const snapshot = await store.saveServer({ ...base, authType: 'sshAgent' })
  await store.upsertServer({ id: snapshot.id, user: 'different-user' })
  await assert.rejects(store.recordConnection(snapshot, { status: 'passed' }), /发生变化/)
  assert.equal((await store.read()).servers[0].lastConnection, undefined)
})
test('SSH uses exact arguments, strict trust and a fixed read-only command', () => {
  const key = join(tmpdir(), 'key with spaces')
  const args = buildSshArgs({ ...base, privateKeyPath: key })
  assert.equal(args[args.indexOf('-i') + 1], key)
  assert.ok(args.includes('StrictHostKeyChecking=yes')); assert.ok(args.includes('BatchMode=yes'))
  assert.ok(args.includes('PermitLocalCommand=no')); assert.deepEqual(args.slice(0, 2), ['-F', 'none'])
  assert.equal(args.at(-1), probeCommand); assert.equal(args.at(-2), base.host)
  assert.throws(() => buildSshArgs({ ...base, host: '-oProxyCommand=bad', privateKeyPath: key }))
  assert.throws(() => buildSshArgs({ ...base, user: '', privateKeyPath: key }), /待补全/)
})
test('private-key paths reject public keys, relative paths, directories and missing files', async () => {
  await assert.rejects(validateKeyPath(join(tmpdir(), 'id_test.pub')), /公钥/)
  await assert.rejects(validateKeyPath('relative-key'), /绝对路径/)
  await assert.rejects(validateKeyPath(tmpdir()), /文件/)
  await assert.rejects(validateKeyPath(join(tmpdir(), 'nonexistent-' + Date.now())))
})
test('connection failures retain actionable categories without bypassing host verification', () => {
  assert.equal(classifyFailure({}, 'WARNING: UNPROTECTED PRIVATE KEY FILE!\nLoad key "key": bad permissions\nPermission denied (publickey).').reason, 'key_permissions')
  assert.equal(classifyFailure({}, 'Load key "key": Permission denied').reason, 'key_unreadable')
  assert.equal(classifyFailure({}, 'Load key "key": invalid format\nPermission denied (publickey).').reason, 'key_format')
  assert.equal(classifyFailure({}, 'Load key "key": incorrect passphrase supplied to decrypt private key').reason, 'key_passphrase')
  assert.equal(classifyFailure({}, 'Host key verification failed.').reason, 'host_key_untrusted')
  assert.equal(classifyFailure({}, 'REMOTE HOST IDENTIFICATION HAS CHANGED').reason, 'host_key_changed')
  assert.equal(classifyFailure({}, 'Permission denied (publickey)').reason, 'authentication')
  assert.equal(classifyFailure({ killed: true }).reason, 'timeout')
  assert.equal(classifyFailure({ name: 'AbortError' }).status, 'canceled')
})
