<script setup>
import { computed, ref } from 'vue'
import { Plus, Bot, ListChecks, Cpu, Brain, ChevronDown, RefreshCw } from 'lucide-vue-next'
const props=defineProps({settings:Object,models:Array,modes:Array,loading:Boolean,error:String,saving:Boolean,attaching:Boolean})
const emit=defineEmits(['settings','refresh','attach'])
const menu=ref(''), anchor=ref(null)
const model=computed(()=>props.models.find(m=>m.model===props.settings.model))
const effortLabels={none:'无',minimal:'极低',low:'低',medium:'中',high:'高',xhigh:'更高',max:'最高',ultra:'Ultra'}
function toggle(which){menu.value=menu.value===which?'':which}
function choose(patch){emit('settings',patch);menu.value=''}
</script>
<template><div class="composer-options" @keydown.esc="menu = ''" @focusout="event => { if (!event.currentTarget.contains(event.relatedTarget)) menu = '' }">
<button type="button" class="compose-option attach-option" aria-label="添加附件" title="添加附件 · 支持拖入文件和粘贴截图" :disabled="attaching" @click="emit('attach')"><Plus :size="16"/><span class="option-label">{{ attaching?'添加中':'附件' }}</span></button>
<div class="option-anchor"><button type="button" class="compose-option" :aria-expanded="menu==='mode'" aria-label="选择工作模式" :title="settings.mode==='plan'?'Plan · 规划模式':'Agent · 执行模式'" :disabled="saving||!models.length" @click="toggle('mode')"><ListChecks v-if="settings.mode==='plan'" :size="15"/><Bot v-else :size="15"/><span class="option-label">{{ settings.mode==='plan'?'Plan':'Agent' }}</span><ChevronDown class="option-chevron" :size="11"/></button><div v-if="menu==='mode'" class="composer-menu" role="menu"><button v-for="mode in modes" :key="mode.mode" type="button" role="menuitemradio" :aria-checked="settings.mode===mode.mode" @click="choose({mode:mode.mode})">{{ mode.mode==='plan'?'Plan · 先研究并制定计划':'Agent · 执行任务' }}</button></div></div>
<div class="option-anchor model-option"><button type="button" class="compose-option" aria-label="选择模型" :aria-expanded="menu==='model'" :title="model?.displayName||error||'获取模型'" :disabled="saving" @click="toggle('model')"><Cpu :size="15"/><span class="option-label">{{ loading?'加载中':model?.displayName||settings.model||'选择模型' }}</span><ChevronDown class="option-chevron" :size="11"/></button><div v-if="menu==='model'" class="composer-menu model-menu" role="menu"><p v-if="error" role="alert">{{ error }}</p><button type="button" @click="emit('refresh')"><RefreshCw :size="13"/>{{ loading?'正在刷新':'刷新模型列表' }}</button><button v-for="item in models" :key="item.id" type="button" role="menuitemradio" :aria-checked="settings.model===item.model" :title="item.description" @click="choose({model:item.model})"><strong>{{ item.displayName }}</strong><small>{{ item.description }}</small></button></div></div>
<div class="option-anchor"><button type="button" class="compose-option" aria-label="选择推理强度" :aria-expanded="menu==='effort'" :title="'推理强度：'+(effortLabels[settings.effort]||settings.effort||'默认')" :disabled="saving||!model" @click="toggle('effort')"><Brain :size="15"/><span class="option-label">{{ effortLabels[settings.effort]||settings.effort||'默认' }}</span><ChevronDown class="option-chevron" :size="11"/></button><div v-if="menu==='effort'" class="composer-menu effort-menu" role="menu"><button v-for="item in model?.supportedReasoningEfforts" :key="item.reasoningEffort" type="button" role="menuitemradio" :aria-checked="settings.effort===item.reasoningEffort" :title="item.description" @click="choose({effort:item.reasoningEffort})">{{ effortLabels[item.reasoningEffort]||item.reasoningEffort }}<small>{{ item.description }}</small></button></div></div>
</div></template>
