<script setup>
import { ref, onMounted, onBeforeUnmount, watch } from 'vue'
import { Folder, FileText, ArrowUp, RefreshCw, Upload, Download, X } from 'lucide-vue-next'
const props = defineProps({ server: Object, initialPath: String })
const emit = defineEmits(['ask'])
const path = ref('/'), entries = ref([]), busy = ref(false), error = ref(''), notice = ref(''), preview = ref(null), selected = ref(null)
let id, disposed = false
const join = name => (path.value === '/' ? '/' : path.value + '/') + name
async function run(fn) { if (busy.value) return; busy.value = true; error.value = ''; try { await fn() } catch (e) { error.value = e.message } finally { busy.value = false } }
async function connect() { if (id) await window.servers.closeTool(id); const result = await window.servers.openTool({ serverId: props.server.id, kind: 'files' }); if (disposed) { await window.servers.closeTool(result.id); return false }; id = result.id; path.value = result.home; return true }
async function list(value = path.value) { const data = await window.servers.listFiles(id, value); path.value = data.path; entries.value = data.entries; selected.value = null; notice.value = data.truncated ? '目录超过 2000 项，仅展示前 2000 项' : `${entries.value.length} 个项目` }
function open(entry) { selected.value = entry; run(async () => { if (entry.directory || entry.link) { try { await list(join(entry.name)); return } catch (e) { if (entry.directory) throw e } }; const data = await window.servers.previewFile(id, join(entry.name)); preview.value = { name: entry.name, path: join(entry.name), ...data } }) }
function transfer(upload) { run(async () => { const result = await window.servers.transferFile(id, upload ? path.value : join(selected.value.name), upload); if (result.completed) { await list(); notice.value = upload ? '上传完成' : '下载完成' } }) }
function retry() { run(async () => { if (await connect()) await list(props.initialPath || path.value) }) }
watch(() => props.initialPath, value => { if (value && id) run(() => list(value)) })
onMounted(retry)
onBeforeUnmount(() => { disposed = true; if (id) window.servers.closeTool(id).catch(() => {}) })
const size = bytes => bytes < 1024 ? bytes + ' B' : bytes < 1048576 ? (bytes / 1024).toFixed(1) + ' KiB' : (bytes / 1048576).toFixed(1) + ' MiB'
</script>
<template><section class="tool-pane files-pane"><form class="tool-toolbar" @submit.prevent="run(() => list())"><button type="button" aria-label="上级目录" :disabled="busy" @click="run(() => list(path.replace(/\/[^/]+\/?$/, '') || '/'))"><ArrowUp :size="15" /></button><input v-model="path" :disabled="busy" aria-label="服务器目录" /><button aria-label="刷新目录" :disabled="busy"><RefreshCw :size="15" /></button><button type="button" :disabled="busy" @click="transfer(true)"><Upload :size="15" />上传</button><button type="button" :disabled="busy || !selected || selected.directory" @click="transfer(false)"><Download :size="15" />下载</button></form><div v-if="error" class="pane-error" role="alert">{{ error }}<button :disabled="busy" @click="retry">重新连接</button></div><div class="tool-caption">{{ server.name }} · {{ busy ? '正在读取 / 传输…' : notice }}</div><div class="file-table"><table><thead><tr><th>名称</th><th>大小</th><th>权限</th><th>修改时间</th></tr></thead><tbody><tr v-for="entry in entries" :key="entry.name" :class="{ selected: selected?.name === entry.name }" @click="selected = entry"><td><button :disabled="busy" @click="open(entry)"><Folder v-if="entry.directory" :size="16" /><FileText v-else :size="16" />{{ entry.name }}{{ entry.link ? ' ↗' : '' }}</button></td><td>{{ entry.directory ? '—' : size(entry.size) }}</td><td>{{ entry.mode }}</td><td>{{ new Date(entry.modified).toLocaleString('zh-CN') }}</td></tr></tbody></table><p v-if="!entries.length && !busy && !error" class="list-empty">此目录为空</p></div><div v-if="preview" class="file-preview"><div class="tool-toolbar"><strong>{{ preview.name }}</strong><span v-if="preview.truncated">仅预览前 256 KiB</span><button @click="emit('ask', { serverId: server.id, text: `请分析服务器 ${server.name} 的文件 ${preview.path}，先只读检查。` })">交给 Copilot</button><button aria-label="关闭文件预览" @click="preview = null"><X :size="16" /></button></div><pre>{{ preview.text }}</pre></div></section></template>
