<script setup>
import { computed, reactive, ref, watch } from 'vue'
import { Clock, Play, Pause, Trash2, Save, Plus, X } from 'lucide-vue-next'
import MarkdownMessage from './MarkdownMessage.vue'
const props=defineProps({taskId:String,snapshot:Object,servers:Array,sessions:Array,models:Array})
const emit=defineEmits(['changed','open','conversation','error'])
const api=window.servers, busy=ref(false), message=ref(''), confirmDelete=ref(false)
const task=computed(()=>props.snapshot.tasks.find(t=>t.id===props.taskId))
const runs=computed(()=>props.snapshot.runs.filter(r=>r.scheduleId===props.taskId).slice().reverse())
const selectedRun=ref(''), run=computed(()=>runs.value.find(r=>r.id===selectedRun.value)||runs.value[0])
const defaults=()=>({name:'',prompt:'',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,rule:{type:'daily',time:'09:00',days:[1,2,3,4,5],at:new Date(Date.now()+3600000).toISOString(),minutes:60},serverIds:[],conversationMode:'new',conversationId:'',operations:'readonly',missedPolicy:'once',notification:'attention',timeoutMinutes:30,enabled:true,settings:null})
const form=reactive(defaults())
watch(()=>props.taskId,()=>{Object.assign(form,defaults(),task.value?structuredClone(JSON.parse(JSON.stringify(task.value))):{});confirmDelete.value=false},{immediate:true})
const models=computed(()=>props.models||[])
const model=computed(()=>models.value.find(m=>m.model===form.settings?.model))
function chooseModel(event){const m=models.value.find(m=>m.model===event.target.value);form.settings=m?{model:m.model,effort:m.defaultReasoningEffort,mode:'default'}:null}
async function act(fn){busy.value=true;message.value='';try{await fn();emit('changed')}catch(e){message.value=e.message}finally{busy.value=false}}
async function save(){await act(async()=>{const value=JSON.parse(JSON.stringify(form));if(!task.value)delete value.id;const saved=await api.saveSchedule(value);emit('open',saved.id);message.value='任务已保存'})}
const time=value=>value?new Date(value).toLocaleString('zh-CN'):'—'
const status=value=>({queued:'排队中',running:'执行中',waiting:'等待确认',completed:'已完成',failed:'失败',interrupted:'已中断',skipped:'已跳过'})[value]||value
</script>
<template>
<section class="scheduler-pane">
  <header class="schedule-heading"><div><div class="eyebrow">AUTOMATION / LOCAL</div><h1>{{ task?.name || '新建定时任务' }}</h1><p>电脑保持开机且 ServerLoom 在后台运行时执行。</p></div><Clock :size="24"/></header>
  <div class="schedule-toolbar"><button v-if="task" :disabled="busy" @click="act(()=>api.runSchedule(task.id))"><Play :size="14"/>立即运行</button><button v-if="task" :disabled="busy" @click="act(async()=>{const enabled=!task.enabled;await api.enableSchedule(task.id,enabled);form.enabled=enabled})"><Pause :size="14"/>{{task.enabled?'暂停任务':'启用任务'}}</button><button v-if="task" @click="confirmDelete=!confirmDelete"><Trash2 :size="14"/>删除</button><span>{{ task?.enabled ? '下次：'+time(task.nextRunAt) : '尚未启用' }}</span></div>
  <div v-if="confirmDelete" class="schedule-confirm">删除任务保留运行记录。<button @click="act(async()=>{await api.removeSchedule(task.id);emit('open','new')})">确认删除</button><button @click="confirmDelete=false">取消</button></div>
  <form class="schedule-form" @submit.prevent="save">
    <label>任务名称<input v-model="form.name" required maxlength="100" placeholder="例如：每天检查家庭服务器"/></label>
    <label>执行指令<textarea v-model="form.prompt" required rows="3" maxlength="30000" placeholder="描述检查内容、异常标准和期望结果"/></label>
    <div class="schedule-grid"><label>频率<select v-model="form.rule.type"><option value="once">一次性</option><option value="interval">固定间隔</option><option value="daily">每天</option><option value="weekly">每周</option></select></label><label>时区<input v-model="form.timezone" required placeholder="Asia/Shanghai"/></label>
    <label v-if="['once','interval'].includes(form.rule.type)">开始时间（ISO，包含时区偏移）<input v-model="form.rule.at" required placeholder="2026-09-15T09:00:00+08:00"/></label><label v-else>当地时间<input v-model="form.rule.time" type="time" required/></label><label v-if="form.rule.type==='interval'">间隔分钟<input v-model.number="form.rule.minutes" type="number" min="1" max="525600" required/></label><label>超时分钟<input v-model.number="form.timeoutMinutes" type="number" min="1" max="1440" required/></label></div>
    <div v-if="form.rule.type==='weekly'" class="schedule-checks"><label v-for="(day,index) in ['日','一','二','三','四','五','六']" :key="day"><input type="checkbox" v-model="form.rule.days" :value="index"/>周{{day}}</label></div>
    <fieldset><legend>目标服务器</legend><div class="schedule-checks"><label v-for="server in servers" :key="server.id"><input type="checkbox" v-model="form.serverIds" :value="server.id"/>{{server.name}}</label><small v-if="!servers.length">尚未添加服务器；可先创建不访问服务器的任务。</small></div></fieldset>
    <div class="schedule-grid"><label>会话<select v-model="form.conversationMode"><option value="new">每次创建独立会话</option><option value="existing">继续指定会话</option></select></label><label v-if="form.conversationMode==='existing'">目标会话<select v-model="form.conversationId" required><option value="" disabled>选择已发送过消息的会话</option><option v-for="s in sessions" :value="s.id" :key="s.id">{{s.title}}</option></select></label><label>操作权限<select v-model="form.operations"><option value="readonly">固定只读检查</option><option value="approval">命令与修改逐次审批</option></select></label><label>漏跑处理<select v-model="form.missedPolicy"><option value="once">恢复后补跑一次</option><option value="skip">跳过漏跑</option></select></label><label>通知<select v-model="form.notification"><option value="attention">失败或需要处理</option><option value="all">完成、失败及需要处理</option><option value="none">不通知（仍保留记录）</option></select></label><label>模型<select :value="form.settings?.model||''" @change="chooseModel"><option value="">运行时默认模型</option><option v-for="m in models" :key="m.model" :value="m.model">{{m.displayName||m.model}}</option></select></label><label v-if="model">推理强度<select v-model="form.settings.effort"><option v-for="e in model.supportedReasoningEfforts" :key="e.reasoningEffort" :value="e.reasoningEffort">{{e.reasoningEffort}}</option></select></label></div>
    <div class="schedule-toolbar"><label class="schedule-inline"><input v-model="form.enabled" type="checkbox"/>启用任务</label><button class="primary" :disabled="busy"><Save :size="14"/>{{busy?'处理中…':'保存任务'}}</button></div>
  </form>
  <p v-if="message" role="status">{{message}}</p>
  <section class="schedule-runs"><h2>运行记录 <small>{{runs.length}}</small></h2><p v-if="!runs.length">首次执行后显示结果、耗时及关联会话。</p><button v-for="r in runs" :key="r.id" class="schedule-run" :class="{selected:run?.id===r.id}" @click="selectedRun=r.id"><span>{{status(r.status)}}</span><time>{{time(r.scheduledAt||r.createdAt)}}</time><small>{{r.startedAt&&r.endedAt?Math.round((Date.parse(r.endedAt)-Date.parse(r.startedAt))/1000)+' 秒':''}}</small></button><div v-if="run" class="schedule-result"><div class="schedule-toolbar"><button @click="emit('conversation',run)">打开关联会话</button><button v-if="['running','waiting','queued'].includes(run.status)" @click="act(()=>api.cancelRun(run.id))"><X :size="14"/>停止任务</button></div><p v-if="run.error" role="status">{{run.error}}</p><MarkdownMessage v-if="run.result" :source="run.result"/><p v-else>尚无输出。</p></div></section>
</section>
</template>
<style scoped>
.scheduler-pane{height:100%;overflow:auto;padding:26px 28px;color:var(--text,#dce5ef)}.schedule-heading{display:flex;justify-content:space-between;gap:16px}.schedule-heading h1{font-size:23px;margin:8px 0}.schedule-heading p,.schedule-toolbar span,.schedule-runs small{color:#94a4b8;font-size:12px}.schedule-toolbar{display:flex;align-items:center;flex-wrap:wrap;gap:8px;margin:15px 0}.schedule-toolbar button{display:flex;align-items:center;gap:6px}.schedule-form label{display:flex;flex-direction:column;gap:7px;font-size:12px;margin-bottom:14px}.schedule-form input,.schedule-form select,.schedule-form textarea{width:100%;background:#0b1017;color:#dce5ef;border:1px solid #293443;border-radius:4px;padding:9px;font:inherit}.schedule-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 14px}.schedule-form fieldset{border:0;border-top:1px solid #293443;padding:12px 0;margin:5px 0 15px}.schedule-form legend{font-size:12px;padding-right:10px}.schedule-checks{display:flex;gap:14px;flex-wrap:wrap}.schedule-checks label,.schedule-form .schedule-inline{flex-direction:row;align-items:center;margin:0}.schedule-checks input,.schedule-inline input{width:auto}.schedule-runs{border-top:1px solid #293443;margin-top:24px;padding-top:16px}.schedule-runs h2{font-size:15px}.schedule-run{display:flex;width:100%;gap:15px;border:0;border-bottom:1px solid #242f3c;border-radius:0;text-align:left;padding:12px 8px}.schedule-run.selected{background:#142b36}.schedule-result{padding:8px 0}.schedule-confirm{padding:12px;background:#2b2420}.schedule-confirm button{margin-left:10px}@media(max-width:1050px){.scheduler-pane{padding:20px 16px}.schedule-grid{grid-template-columns:1fr}}
</style>
