<script setup>
import { computed, ref, nextTick, onMounted, onBeforeUnmount } from 'vue'
import { Server, Plus, Search, ChevronRight, MoreHorizontal, Upload, Download, FolderPlus, X } from 'lucide-vue-next'
const api = window.servers
const props = defineProps({ servers: Array, groups: Array, selected: String })
const emit = defineEmits(['select', 'terminal', 'open', 'edit', 'chat', 'migrate', 'import', 'changed', 'error'])
const query = ref(''), collapsed = ref({}), menu = ref(null), menuEl = ref(null), groupDialog = ref(null), name = ref(''), groupId = ref(''), busy = ref(false), localError = ref('')
const rows = computed(() => [...props.groups, { id: '', name: '未分组' }].map(g => ({ ...g, servers: props.servers.filter(s => (s.groupId || '') === g.id && `${s.name} ${s.host} ${g.name}`.toLowerCase().includes(query.value.toLowerCase())) })).filter(g => !query.value || g.servers.length))
async function run(fn) { busy.value = true; try { await fn(); emit('changed') } catch (e) { emit('error', e.message) } finally { busy.value = false; menu.value = null } }
async function context(event, server, group) { event.preventDefault(); menu.value = { server, group, x: Math.max(4, Math.min(event.clientX, innerWidth - 235)), y: Math.max(4, Math.min(event.clientY, innerHeight - 390)) }; await nextTick(); menuEl.value?.querySelector('button')?.focus() }
function closeMenu(event) { if (!menuEl.value?.contains(event.target)) menu.value = null }
function key(event) { if (event.key === 'Escape') menu.value = null; if (menu.value && ['ArrowDown', 'ArrowUp'].includes(event.key) && event.target.tagName !== 'SELECT') { event.preventDefault(); const buttons = [...menuEl.value.querySelectorAll('button:not(:disabled), select')], index = buttons.indexOf(document.activeElement); buttons[(index + (event.key === 'ArrowDown' ? 1 : -1) + buttons.length) % buttons.length]?.focus() } }
function action(kind) { const server = menu.value.server; menu.value = null; if (kind === 'edit' || kind === 'chat') emit(kind, server); else if (kind === 'migrate') emit('migrate', [server.id]); else if (kind === 'overview') emit('select', server); else emit('open', kind, server) }
function editGroup(group) { groupId.value = group?.id || ''; name.value = group?.name || ''; localError.value = ''; menu.value = null; groupDialog.value.showModal(); nextTick(() => groupDialog.value.querySelector('input').focus()) }
async function saveGroup() { busy.value = true; localError.value = ''; try { await api.saveGroup({ id: groupId.value || undefined, name: name.value }); emit('changed'); groupDialog.value.close() } catch (e) { localError.value = e.message } finally { busy.value = false } }
function drag(event, id) { event.dataTransfer.setData('application/x-servers-id', id); event.dataTransfer.effectAllowed = 'move' }
function drop(event, groupId) { const id = event.dataTransfer.getData('application/x-servers-id'); if (props.servers.some(s => s.id === id)) run(() => api.moveServer(id, groupId)) }
onMounted(() => { document.addEventListener('pointerdown', closeMenu); document.addEventListener('keydown', key) })
onBeforeUnmount(() => { document.removeEventListener('pointerdown', closeMenu); document.removeEventListener('keydown', key) })
</script>
<template><div class="server-sidebar-content"><label class="search"><Search :size="14" /><input v-model="query" placeholder="搜索服务器或分组" aria-label="搜索服务器" /></label><div class="section-label">资产 <span>{{ servers.length }}</span><button aria-label="新建分组" title="新建分组" @click="editGroup()"><FolderPlus :size="15" /></button><button aria-label="添加服务器" title="添加服务器" @click="emit('edit')"><Plus :size="15" /></button></div><div class="server-list"><section v-for="group in rows" :key="group.id" class="server-group" @dragover.prevent @drop.prevent="drop($event, group.id)"><div class="group-heading" @contextmenu="context($event, null, group)"><button :aria-expanded="!collapsed[group.id] || !!query" @click="collapsed[group.id] = !collapsed[group.id]"><ChevronRight :size="13" :class="{ rotated: !collapsed[group.id] || query }" /><span>{{ group.name }}</span><small>{{ group.servers.length }}</small></button><button :aria-label="'分组菜单 ' + group.name" @click="context($event, null, group)"><MoreHorizontal :size="14" /></button></div><div v-show="!collapsed[group.id] || query"><div v-for="server in group.servers" :key="server.id" class="server-entry"><button class="server-row" :class="{ active: selected === server.id }" draggable="true" @dragstart="drag($event, server.id)" @click="emit('select', server)" @dblclick="emit('terminal', server)" @contextmenu="context($event, server)"><Server :size="16" /><span>{{ server.name }}<small>{{ server.host }}</small></span></button><button class="server-more" :aria-label="'服务器菜单 ' + server.name" @click="context($event, server)"><MoreHorizontal :size="14" /></button></div><p v-if="!group.servers.length && !query" class="group-empty">拖动服务器到此分组</p></div></section><p v-if="!rows.length" class="list-empty">没有匹配的服务器</p></div><div class="asset-bottom"><button :disabled="!servers.length" @click="emit('migrate', servers.map(s => s.id))"><Upload :size="14" />迁移到我的设备</button><button @click="emit('import')"><Download :size="14" />导入连接包</button></div>
<Teleport to="body"><div v-if="menu" ref="menuEl" class="server-context" role="menu" :style="{ left: menu.x + 'px', top: menu.y + 'px' }"><template v-if="menu.server"><strong>{{ menu.server.name }}</strong><button role="menuitem" @click="action('overview')">打开概览</button><button role="menuitem" :disabled="menu.server.configStatus !== 'configured'" @click="action('ssh')">SSH 终端</button><button role="menuitem" :disabled="menu.server.configStatus !== 'configured'" @click="action('files')">文件管理器</button><button role="menuitem" :disabled="menu.server.configStatus !== 'configured'" @click="action('bandwidth')">带宽监控</button><button role="menuitem" @click="action('chat')">新建 Copilot 对话</button><button role="menuitem" @click="action('edit')">编辑服务器</button><label>移动到分组<select aria-label="移动到分组" :value="menu.server.groupId || ''" @change="run(() => api.moveServer(menu.server.id, $event.target.value))"><option value="">未分组</option><option v-for="group in groups" :key="group.id" :value="group.id">{{ group.name }}</option></select></label><button role="menuitem" @click="action('migrate')">迁移到我的设备…</button></template><template v-else><strong>{{ menu.group.name }}</strong><button v-if="menu.group.id" role="menuitem" @click="editGroup(menu.group)">重命名分组</button><button v-if="menu.group.id" role="menuitem" @click="run(() => api.reorderGroup(menu.group.id, -1))">上移分组</button><button v-if="menu.group.id" role="menuitem" @click="run(() => api.reorderGroup(menu.group.id, 1))">下移分组</button><button role="menuitem" :disabled="!menu.group.servers.length" @click="emit('migrate', menu.group.servers.map(s => s.id)); menu = null">迁移此分组…</button><button v-if="menu.group.id" role="menuitem" @click="run(() => api.removeGroup(menu.group.id))">删除分组（保留服务器）</button></template></div></Teleport>
<dialog ref="groupDialog"><form @submit.prevent="saveGroup"><div class="dialog-header"><h2>{{ groupId ? '重命名分组' : '新建分组' }}</h2><button type="button" aria-label="关闭分组表单" @click="groupDialog.close()"><X :size="18" /></button></div><label>分组名称<input v-model="name" required maxlength="40" /></label><p v-if="localError" class="form-error" role="alert">{{ localError }}</p><div class="dialog-actions"><button type="button" @click="groupDialog.close()">取消</button><button class="primary" :disabled="busy">保存分组</button></div></form></dialog></div></template>
