import {_electron as electron} from 'playwright'
import {resolve,join} from 'node:path'
import {mkdir,mkdtemp,writeFile} from 'node:fs/promises'
import assert from 'node:assert/strict'
await mkdir('artifacts',{recursive:true});const data=await mkdtemp(resolve('artifacts/copilot-ui-')),file=join(data,'error.log');await writeFile(file,'fixture log 5831')
const app=await electron.launch({args:['.'],env:{...process.env,SERVERS_TEST_DATA:data,SERVERS_DEV:'0'}})
try{const page=await app.firstWindow(),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await page.getByRole('heading',{name:'选择服务器，开始工作。'}).waitFor();await page.waitForFunction(()=>document.querySelector('[aria-label="选择工作模式"]')?.disabled===false)
 const catalog=await page.evaluate(()=>window.servers.catalog());assert.ok(catalog.models.length>1)
 await page.getByLabel('选择模型',{exact:true}).click();await page.getByRole('menuitemradio').filter({hasText:catalog.models[1].displayName}).click();await page.getByLabel('选择推理强度',{exact:true}).click();await page.getByRole('menuitemradio').first().click();await page.getByLabel('选择工作模式',{exact:true}).click();await page.getByRole('menuitemradio',{name:'Plan · 先研究并制定计划'}).click();await page.waitForFunction(()=>document.querySelector('[aria-label="选择工作模式"]').title.startsWith('Plan'))
 await page.waitForFunction(()=>!!JSON.parse(localStorage.getItem('servers-workbench')||'{}').conversationId);const id=await page.evaluate(()=>JSON.parse(localStorage.getItem('servers-workbench')).conversationId)
 await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]})},file)
 await page.getByLabel('添加附件',{exact:true}).click();await page.locator('.attachment-chips').getByRole('button',{name:'error.log',exact:true}).waitFor();await page.locator('.attachment-chips').getByRole('button',{name:'error.log',exact:true}).click();await page.getByRole('dialog',{name:'附件预览'}).getByText('fixture log 5831',{exact:true}).waitFor();await page.keyboard.press('Escape')
 await page.reload();await page.locator('.attachment-chips').getByRole('button',{name:'error.log',exact:true}).waitFor();assert.match(await page.getByLabel('选择工作模式',{exact:true}).getAttribute('title'),/^Plan/)
 await page.getByLabel('新建对话',{exact:true}).click();assert.equal(await page.locator('.attachment-chips').count(),0);await page.getByLabel('切换会话列表',{exact:true}).click();await page.locator('.session-row').last().click();await page.locator('.attachment-chips').getByRole('button',{name:'error.log',exact:true}).waitFor();await page.getByLabel('收起会话列表',{exact:true}).click()
 await page.getByLabel('移除附件 error.log').click();await page.locator('.attachment-chips').waitFor({state:'hidden'})
 await page.evaluate(()=>{const el=document.createElement('input');el.type='file';el.id='fixture-file';document.body.appendChild(el)});await page.locator('#fixture-file').setInputFiles(file);await page.evaluate(()=>{const transfer=new DataTransfer();transfer.items.add(document.querySelector('#fixture-file').files[0]);document.querySelector('.composer').dispatchEvent(new DragEvent('drop',{bubbles:true,dataTransfer:transfer}));document.querySelector('#fixture-file').remove()});await page.locator('.attachment-chips').getByRole('button',{name:'error.log',exact:true}).waitFor()
 await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=40;canvas.height=40;canvas.getContext('2d').fillRect(0,0,40,40);const blob=await new Promise(r=>canvas.toBlob(r));const transfer=new DataTransfer();transfer.items.add(new File([blob],'clip.png',{type:'image/png'}));document.querySelector('.composer textarea').dispatchEvent(new ClipboardEvent('paste',{bubbles:true,clipboardData:transfer}))});await page.locator('.attachment-chips').getByRole('button',{name:'截图.png',exact:true}).waitFor()
 await app.evaluate(({ipcMain,BrowserWindow},id)=>{ipcMain.removeHandler('copilot:limits');ipcMain.handle('copilot:limits',()=>({rateLimitsByLimitId:{codex:{limitId:'codex',primary:{usedPercent:25,windowDurationMins:300,resetsAt:Math.floor(Date.now()/1000)+3600},secondary:{usedPercent:40,windowDurationMins:10080,resetsAt:Math.floor(Date.now()/1000)+86400}},extra:{limitId:'extra',primary:null,secondary:null}}}));const w=BrowserWindow.getAllWindows()[0];w.webContents.send('runtime:event',{method:'account/rateLimits/updated',params:{rateLimits:{}}});w.webContents.send('runtime:event',{conversationId:id,method:'thread/goal/updated',params:{goal:{objective:'检查服务器运行状态',status:'active',tokensUsed:1200,timeUsedSeconds:180,tokenBudget:10000}}});w.webContents.send('runtime:event',{conversationId:id,method:'turn/plan/updated',params:{turnId:'fixture',plan:[{step:'检查连接',status:'completed'},{step:'汇总状态',status:'inProgress'}]}});w.webContents.send('runtime:event',{conversationId:id,method:'item/completed',params:{turnId:'fixture',item:{id:'plan-fixture',type:'plan',text:'## 巡检计划\n\n1. 检查连接\n2. 汇总结果'}}})},id)
 await page.getByRole('button',{name:/检查服务器运行状态/}).click();await page.getByText('汇总状态',{exact:false}).first().waitFor();await page.getByLabel('查看套餐余量',{exact:true}).click();await page.getByRole('region',{name:'套餐余量详情'}).getByText('75% 剩余',{exact:true}).waitFor();await page.screenshot({path:'artifacts/copilot-quota.png'});await page.keyboard.press('Escape')
 await page.getByLabel('选择模型',{exact:true}).click();await page.screenshot({path:'artifacts/copilot-models.png'});await page.keyboard.press('Escape')
 const splitter=page.getByRole('separator',{name:'调整 Copilot 宽度'});await splitter.focus();for(let i=0;i<6;i++)await page.keyboard.press('ArrowRight');assert.equal(await page.getByLabel('选择工作模式',{exact:true}).locator('.option-label').isVisible(),false);await page.screenshot({path:'artifacts/copilot-compact.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)
 await app.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.setSize(960,720);w.webContents.setZoomFactor(1.5)});await page.waitForFunction(()=>getComputedStyle(document.querySelector('.quota-summary')).display==='none');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.getByLabel('查看套餐余量').locator('.quota-summary').isVisible(),false);if(await page.locator('.asset-panel').isVisible())await page.getByLabel('切换侧边栏',{exact:true}).click();await page.locator('.asset-panel').waitFor({state:'hidden'});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.waitForFunction(()=>{const r=document.querySelector('.send-button').getBoundingClientRect();return r.bottom<=innerHeight&&r.right<=innerWidth});const zoom=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toDataURL());await writeFile('artifacts/copilot-zoom.png',Buffer.from(zoom.split(',')[1],'base64'))
 assert.deepEqual(errors,[]);console.log('PASS model/effort/mode menus, session settings, attachment select/drop/paste/preview/reload, native event rendering, quota statusbar and panel-width icon folding')
}catch(e){const page=await app.firstWindow();console.log((await page.locator('body').innerText()).slice(-5000));await page.screenshot({path:'artifacts/copilot-failure.png'});throw e}finally{await app.close()}
